### ISSUE TITLE
P106 090 

### ISSUE THREAD

**Issue by apomaxos** [iiiyx/p106-100-p104-100#2]
Unable to modify the strings to use a zotac p106-090 3gb i have a triangle of driver error and i cant seem able to make this work , can you post a modified inf for p106 90

**Comment by iiiyx** [comment]
1. Download the original driver https://www.guru3d.com/files-get/geforce-417-22-whql-driver-download,1.html
2. Extract it.
3. Open Display.Driver/nv_dispi.inf and find your device ID: _NVIDIA_DEV.**1C09** = "NVIDIA P106-090"_
It's **1C09**
4. Find analogus device ID: _NVIDIA_DEV.**1C02** = "NVIDIA GeForce GTX 1060 3GB"_
It's **1C02**
5. Find section number for analogus device ID:
_%NVIDIA_DEV.1C02%           = Section**108**, PCI\VEN_10DE&DEV_1C02_
and
_%NVIDIA_DEV.1C02%           = Section**107**, PCI\VEN_10DE&DEV_1C02_
6. Replace section number for your device ID with section number for analogus device:
I.e. replace every line _%NVIDIA_DEV.**1C09**%           = Section**110**, PCI\VEN_10DE&DEV_1C09_
with _%NVIDIA_DEV.**1C09**%           = Section**108**, PCI\VEN_10DE&DEV_1C09_
and line _%NVIDIA_DEV.**1C09**%           = Section**109**, PCI\VEN_10DE&DEV_1C09_
with _%NVIDIA_DEV.**1C09**%           = Section**107**, PCI\VEN_10DE&DEV_1C09_
7. Save and run driver installer if every other step from the README.md is done.

P.S. you can't use drivers newer than 417.22
P.P.S. if you've done it exactly as I wrote, then sorry I can't help.
P.P.P.S take a look at a newer "ready" inf file. Now it's for NVIDIA 417.22 driver version and contains all needed changes. Basically all mining cards are described there by Section110 (and 109), so I just changed it everywhere to Section108 (and 107), which describes GTX1060/1070 cards.

**Comment by iiiyx** [comment]
#3

**Comment by SirTETESpain** [comment]
Hello, I have the same graphics card, but the triangle with the error code 10 appears.

I have unzipped the driver installation package for this topic and modified the .inf file before installing the drivers, but it failed to install the drivers from setup.exe.

I have managed to install the graphics card manually using the unzipped and modified files and so it does install, but I get the triangle with the error code 10.

Any idea what the problem may be?

I have tried to uninstall everything with DDU and try again, but using the package's setup.exe it gives me an error and it is installed manually but I get the error code 10.

My PC is the following:

Intel I7 7700K No OverClock
MB: Gigabyte GA-Z270-Gaming K3
RAM: G Skill Aegis DDR4 @ 2133Mhz
Graphics Card Principal: Asus Strix R9 380 4Gb
2 Graphics  Card: Zotac 1060 3Gb Mining Edition (ZT-M10610A-10B)


I have the first graphics card (AMD ASUS R9-380) connected to the first PCI-E x16 and the Zotac 1060 3gb mining edition graphics card is connected to the second PCI-E x16.


I appreciate you helping me to install and use my graphics card.

Thanks

**Comment by iiiyx** [comment]
Hi @SirTETESpain, where are you located in Spain?
As far as I understand, you have installed the original drivers, but you're still getting this error code 10, right? If so, then there is something wrong with the card.
If the original drivers work fine, then we just need to correctly adjust the _.inf_ file. And I can help you with that.
Also, it might be useful to repeat all the steps using **only** one card installed - the mining one.

**Comment by iiiyx** [comment]
I found out here https://www.ixbt.com/news/2017/10/04/inno3d-p106-090-crypto-mining-board-geforce-gtx-1050-ti-gtx-1060.html (sorry, it's in Russian) that p106-090 has the same processor - GP106, but has fewer CUDA cores and has lower frequencies. So, it looks more like GTX 1050 Ti than GTX 1060 but having a 192-bit bus. Maybe these differences are the reason for error code 10...

**Comment by SirTETESpain** [comment]
Hello, yesterday I spent the whole night modifying the .inf file you
mention but I still did not install the graphics card. Please, if you can,
modify the .inf file and send it to me telling me what version of the
drivers you have used so that I can download them from the nvidia website
or send me a link with the driver that I have to install. Currently the
card that I bought from you I cannot use it and I need it.

Thank you very much

**Comment by JKBrnew** [comment]
Também estou com este problema, não consigo instalar p106-90 on ubuntu 20.04
