### ISSUE TITLE
Does not work with AMD Processor and AMD Motherboard

### ISSUE THREAD

**Issue by Danishagn** [iiiyx/p106-100-p104-100#4]
Dear Sir,

Its all work fine with INTEL Processor and motherboard but when i check with AMD processor and Amd motherboard not working... i cannot see graphic setting in display properties... please tell me how to use P106-100 card with AMD Processor?

**Comment by iiiyx** [comment]
Hi @Danishagn 
Sorry, there is no known way for me to achieve this with AMD CPU.
